
server:
  #服务器端口号
  port: 8080

# 数据源
spring:

  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/homework
    url: jdbc:mysql://localhost:3306/homework?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

#  profiles:
#    active: dev

#配置mybatis的sql映射文件路径
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.homework.bean

#日志
logging:
  level:
    com.example.homework: debug
